### ISSUE TITLE
Missing Annotation on PersonRepository

### ISSUE THREAD

**Issue by kentoj** [techdev-solutions/jaxenter-showcase#1]
Is there supposed to be an `@Repository` or `@RestRepository` annotation on your repository class?

**Comment by kentoj** [comment]
It worked for me without it. I was having issues finding my repository though it turned out to be my PersistenceConfiguration.java needed to be in a higher package than my PersonRepository.java in order for the component scanning to work properly.

Everything works without a @Repository annotation.

**Comment by FrontierPsychiatrist** [comment]
Hi!
Yes, the [auto configuration](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-data-jpa-repositories) for Spring Data JPA repositories should pick them up automatically. `@ComponentScan` takes the package of its class as the base scanning package as a default, so you're right, the configuration must be in a higher or equal package of the repositories.
